In [4]:
import flordb as flor
import pandas as pd

# This is the "long" table of log records (one row per log event)
records = flor.dataframe("event")  # try a likely key you logged
records.tail(20)

Empty DataFrame
Columns: [projid, tstamp, filename, event]
Index: []

In [5]:
import flordb as flor

df = flor.dataframe()     # if supported in your version, this returns a “full pivot”
df.head()

No default values to pivot on

Empty DataFrame
Columns: []
Index: []